<?php

return [
    'Aceh' => ['Banda Aceh', 'Lhokseumawe', 'Langsa', 'Subulussalam', 'Sabang'],
    'Sumatera Utara' => ['Medan', 'Binjai', 'Tebing Tinggi', 'Pematangsiantar', 'Padang Sidempuan', 'Gunungsitoli', 'Sibolga'],
    'Sumatera Barat' => ['Padang', 'Bukittinggi', 'Solok', 'Sawahlunto', 'Payakumbuh'],
    'Riau' => ['Pekanbaru', 'Dumai'],
    'Kepulauan Riau' => ['Batam', 'Tanjungpinang'],
    'Jambi' => ['Jambi', 'Sungai Penuh'],
    'Bengkulu' => ['Bengkulu'],
    'Sumatera Selatan' => ['Palembang', 'Lubuklinggau', 'Prabumulih', 'Pagar Alam'],
    'Lampung' => ['Bandar Lampung', 'Metro'],
    'Bangka Belitung' => ['Pangkalpinang'],
    'DKI Jakarta' => ['Jakarta Pusat', 'Jakarta Utara', 'Jakarta Selatan', 'Jakarta Barat', 'Jakarta Timur', 'Kepulauan Seribu'],
    'Jawa Barat' => ['Bandung', 'Bogor', 'Bekasi', 'Depok', 'Cimahi', 'Cirebon', 'Sukabumi', 'Karawang', 'Tasikmalaya', 'Banjar'],
    'Jawa Tengah' => ['Semarang', 'Surakarta', 'Salatiga', 'Magelang', 'Tegal', 'Pekalongan'],
    'DI Yogyakarta' => ['Yogyakarta'],
    'Jawa Timur' => ['Surabaya', 'Malang', 'Madiun', 'Kediri', 'Blitar', 'Probolinggo', 'Pasuruan', 'Batu'],
    'Banten' => ['Serang', 'Cilegon', 'Tangerang', 'Tangerang Selatan'],
    'Bali' => ['Denpasar'],
    'Nusa Tenggara Barat' => ['Mataram', 'Bima'],
    'Nusa Tenggara Timur' => ['Kupang'],
    'Kalimantan Barat' => ['Pontianak', 'Singkawang'],
    'Kalimantan Tengah' => ['Palangka Raya'],
    'Kalimantan Selatan' => ['Banjarmasin', 'Banjarbaru'],
    'Kalimantan Timur' => ['Balikpapan', 'Samarinda', 'Bontang'],
    'Kalimantan Utara' => ['Tarakan'],
    'Sulawesi Utara' => ['Manado', 'Tomohon', 'Bitung', 'Kotamobagu'],
    'Gorontalo' => ['Gorontalo'],
    'Sulawesi Tengah' => ['Palu'],
    'Sulawesi Selatan' => ['Makassar', 'Parepare', 'Palopo'],
    'Sulawesi Tenggara' => ['Kendari', 'Baubau'],
    'Sulawesi Barat' => ['Mamuju'],
    'Maluku' => ['Ambon', 'Tual'],
    'Maluku Utara' => ['Ternate', 'Tidore Kepulauan'],
    'Papua' => ['Jayapura'],
    'Papua Barat' => ['Sorong'],
    'Papua Tengah' => [],
    'Papua Pegunungan' => [],
    'Papua Selatan' => [],
    'Papua Barat Daya' => [],
    'Negara' => [
        'Afghanistan', 'Afrika Selatan', 'Albania', 'Algeria', 'Amerika Serikat',
        'Andorra', 'Angola', 'Antigua dan Barbuda', 'Arab Saudi', 'Argentina',
        'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahama',
        'Bahrain', 'Bangladesh', 'Barbados', 'Belanda', 'Belarus',
        'Belgia', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
        'Bosnia dan Herzegovina', 'Botswana', 'Brasil', 'Brunei', 'Bulgaria',
        'Burkina Faso', 'Burundi', 'Chad', 'Chili', 'China',
        'Denmark', 'Djibouti', 'Dominika', 'Ekuador', 'El Salvador',
        'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Filipina',
        'Finlandia', 'Gabon', 'Gambia', 'Georgia', 'Ghana',
        'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
        'Haiti', 'Honduras', 'Hong Kong', 'Hongaria', 'India',
        'Indonesia', 'Inggris', 'Irak', 'Iran', 'Irlandia',
        'Islandia', 'Israel', 'Italia', 'Jamaika', 'Jepang',
        'Jerman', 'Yordania', 'Kamboja', 'Kamerun', 'Kanada',
        'Kazakhstan', 'Kenya', 'Kirgizstan', 'Kiribati', 'Kolombia',
        'Komoro', 'Kongo', 'Korea Selatan', 'Korea Utara', 'Kosta Rika',
        'Kroasia', 'Kuba', 'Kuwait', 'Laos', 'Latvia',
        'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
        'Lituania', 'Luksemburg', 'Madagaskar', 'Maladewa', 'Malawi',
        'Malaysia', 'Mali', 'Malta', 'Maroko', 'Marshall Islands',
        'Mauritania', 'Mauritius', 'Meksiko', 'Mesir', 'Moldova',
        'Monako', 'Mongolia', 'Montenegro', 'Mozambik', 'Myanmar',
        'Namibia', 'Nauru', 'Nepal', 'Nicaragua', 'Niger',
        'Nigeria', 'Norwegia', 'Oman','Palestina', 'Pakistan', 'Palau',
        'Panama', 'Papua Nugini', 'Paraguay', 'Perancis', 'Peru',
        'Polandia', 'Portugal', 'Qatar', 'Republik Afrika Tengah', 'Republik Ceko',
        'Republik Demokratik Kongo', 'Republik Dominika', 'Rumania', 'Rusia', 'Rwanda',
        'Saint Kitts dan Nevis', 'Saint Lucia', 'Saint Vincent dan Grenadines', 'Samoa', 'San Marino',
        'Sao Tome dan Principe', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone',
        'Singapura', 'Siprus', 'Slovakia', 'Slovenia', 'Solomon Islands',
        'Somalia', 'Spanyol', 'Sri Lanka', 'Sudan', 'Sudan Selatan',
        'Suriname', 'Swaziland', 'Swedia', 'Swiss', 'Syria',
        'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor Leste',
        'Togo', 'Tonga', 'Trinidad dan Tobago', 'Tunisia', 'Turki',
        'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraina', 'Uni Emirat Arab',
        'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
        'Yaman', 'Yunani', 'Zambia', 'Zimbabwe'
    ],
];
